apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-java-app
  namespace: default
spec:
  interval: 10s
  ref:
    branch: master
  url: "https://github.com/NizarNasraoui1/learn-fluxcd.git"

