apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-java-app
  namespace: flux-system
spec:
  interval: 10s
  url: "https://github.com/NizarNasraoui1/learn-flux.git"
  ref:
    branch: master
  

