apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-java-app
  namespace: flux-system
spec:
  interval: 10s
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: my-java-app
  path: "./java/k8s"
  prune: true
  



  