apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-java-app
  namespace: flux-system
spec:
  interval: 10s
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-java-app