apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-java-app
  namespace: default
spec:
  interval: 10s
  path: "./java/k8s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-java-app