apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      name: api
      labels:
        app: springapp
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000 # Adjust this as needed based on your container's user configuration
      containers:
      - name: springapp
        image: api-flux:1.0.2
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
